/****************************************************************************
*   Generated by ACUITY 5.7.0
*   Match ovxlib 1.1.18
*
*   Neural Network global header file
****************************************************************************/
#ifndef _VNN_GLOBAL_H_
#define _VNN_GLOBAL_H_

/*
 * This file will be deprecated in the future
 */

#endif
