/****************************************************************************
*   Generated by ACUITY 5.7.0
*   Match ovxlib 1.1.18
*
*   Neural Network appliction post-process header file
****************************************************************************/
#ifndef _VNN_POST_PROCESS_H_
#define _VNN_POST_PROCESS_H_
#ifdef __cplusplus
extern "C"{
#endif

vsi_status vnn_PostProcessVgg(vsi_nn_graph_t *graph, char *priorPath, char *threshold);

#ifdef __cplusplus
}
#endif
#endif
