/****************************************************************************
*   Generated by ACUITY 5.7.0
*
*   Neural Network application project entry file
****************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <math.h>
#include <assert.h>
#include <VX/vx_khr_cnn.h>
#include <VX/viv_nn_compatibility.h>
#include <VX/vx_khr_import_kernel.h>

#include "vnn_utils.h"

#define _CHECK_OBJ(ptr, label) \
do \
{ \
    if ((ptr) == NULL) \
    { \
        printf("create fail %d\n", __LINE__); \
        goto label; \
    } \
} while(0)

#define _CHECK_STATUS(status, label) \
do \
{ \
    if (status != VX_SUCCESS) \
    { \
        printf("process fail %d\n", __LINE__); \
        goto label; \
    } \
} while(0)


/*-------------------------------------------
                  Main Functions
-------------------------------------------*/

int main
    (
    int argc,
    char **argv
    )
{
    vx_context  context = NULL;
    vx_graph    graph = NULL;
    vx_kernel   kernel = NULL;
    vx_node     node = NULL;
    vx_status   status = VX_FAILURE;

    vx_tensor input_93_out0 = NULL;
    vx_tensor attach_Concat_Concat_149_out0_1_out0 = NULL;
    vx_tensor attach_Softmax_Softmax_150_out0_0_out0 = NULL;

    vx_tensor_create_params_t ts_params;
    vx_uint32  sizes[6];


    if(argc < 3)
    {
        printf("Usage: %s nb file, input files...\n", argv[0]);
        return -1;
    }

    context = vxCreateContext();
    _CHECK_OBJ(context, exit);

    graph = vxCreateGraph(context);
    _CHECK_OBJ(graph, exit);

    kernel = vxImportKernelFromURL(context, VX_VIVANTE_IMPORT_KERNEL_FROM_FILE, argv[1]);
    status = vxGetStatus((vx_reference)kernel);
    _CHECK_STATUS(status, exit);

    node = vxCreateGenericNode(graph, kernel);
    status = vxGetStatus((vx_reference)node);
    _CHECK_STATUS(status, exit);

    /* @input_93:out0 */
    sizes[0] = 300;
    sizes[1] = 300;
    sizes[2] = 3;
    sizes[3] = 1;
    ts_params.num_of_dims = 4;
    ts_params.sizes = sizes;
    ts_params.quant_format = VX_QUANT_AFFINE_SCALE;
    ts_params.quant_data.affine.scale = 1.074509859;
    ts_params.quant_data.affine.zeroPoint = 114;
    ts_params.data_format = VX_TYPE_UINT8;
    input_93_out0 = vxCreateTensor2(context, & ts_params, sizeof(ts_params));
    _CHECK_OBJ(input_93_out0, exit);


    /* @attach_Concat_Concat_149/out0_1:out0 */
    sizes[0] = 4;
    sizes[1] = 8732;
    sizes[2] = 1;
    ts_params.num_of_dims = 3;
    ts_params.sizes = sizes;
    ts_params.quant_format = VX_QUANT_AFFINE_SCALE;
    ts_params.quant_data.affine.scale = 0.040214974;
    ts_params.quant_data.affine.zeroPoint = 155;
    ts_params.data_format = VX_TYPE_UINT8;
    attach_Concat_Concat_149_out0_1_out0 = vxCreateTensor2(context, & ts_params, sizeof(ts_params));
    _CHECK_OBJ(attach_Concat_Concat_149_out0_1_out0, exit);


    /* @attach_Softmax_Softmax_150/out0_0:out0 */
    sizes[0] = 21;
    sizes[1] = 8732;
    sizes[2] = 1;
    ts_params.num_of_dims = 3;
    ts_params.sizes = sizes;
    ts_params.quant_format = VX_QUANT_NONE;
    ts_params.data_format = VX_TYPE_FLOAT16;
    attach_Softmax_Softmax_150_out0_0_out0 = vxCreateTensor2(context, & ts_params, sizeof(ts_params));
    _CHECK_OBJ(attach_Softmax_Softmax_150_out0_0_out0, exit);



    status |= vxSetParameterByIndex(node, 0, (vx_reference)input_93_out0);
    status |= vxSetParameterByIndex(node, 1, (vx_reference)attach_Concat_Concat_149_out0_1_out0);
    status |= vxSetParameterByIndex(node, 2, (vx_reference)attach_Softmax_Softmax_150_out0_0_out0);
    _CHECK_STATUS(status, exit);


    status = vxVerifyGraph(graph);
    _CHECK_STATUS(status, exit);

    status = vnn_LoadTensorFromFile(input_93_out0,argv[2]);
    _CHECK_STATUS(status, exit);

    status = vxProcessGraph(graph);
    _CHECK_STATUS(status, exit);

    status = vnn_ShowTensorTop5(attach_Concat_Concat_149_out0_1_out0);
    _CHECK_STATUS(status, exit);
    status = vnn_SaveTensorToFileAsFloat32(attach_Concat_Concat_149_out0_1_out0,"attach_Concat_Concat_149_out0_1_out0");
    _CHECK_STATUS(status, exit);
    status = vnn_ShowTensorTop5(attach_Softmax_Softmax_150_out0_0_out0);
    _CHECK_STATUS(status, exit);
    status = vnn_SaveTensorToFileAsFloat32(attach_Softmax_Softmax_150_out0_0_out0,"attach_Softmax_Softmax_150_out0_0_out0");
    _CHECK_STATUS(status, exit);


exit:
    if(input_93_out0 != NULL)
        vxReleaseTensor(&input_93_out0);
    if(attach_Concat_Concat_149_out0_1_out0 != NULL)
        vxReleaseTensor(&attach_Concat_Concat_149_out0_1_out0);
    if(attach_Softmax_Softmax_150_out0_0_out0 != NULL)
        vxReleaseTensor(&attach_Softmax_Softmax_150_out0_0_out0);
    if (kernel != NULL)
        vxReleaseKernel(&kernel);
    if (node != NULL)
        vxReleaseNode(&node);
    if (graph != NULL)
        vxReleaseGraph(&graph);
    if (context != NULL)
        vxReleaseContext(&context);
    return 0;
}
